import type { NodeType, NodeCategory, NodeShape, Size } from '@platform/diagram-schema';

export type NodeDefinition = {
  type: NodeType;
  defaultShape: NodeShape;
  label: string;
  category: NodeCategory;
  defaultSize: Size;
  defaultIcon: string;
  description: string;
};

export const nodeDefinitions: Record<NodeType, NodeDefinition> = {
  user: {
    type: 'user',
    defaultShape: 'user_avatar',
    label: 'User',
    category: 'client',
    defaultSize: { width: 140, height: 96 },
    defaultIcon: 'user',
    description: 'Human actor, web user, or client application',
  },
  browser: {
    type: 'browser',
    defaultShape: 'browser_window',
    label: 'Web Browser',
    category: 'client',
    defaultSize: { width: 170, height: 95 },
    defaultIcon: 'browser',
    description: 'Single Page Application or Desktop Browser client',
  },
  mobile: {
    type: 'mobile',
    defaultShape: 'device_mobile',
    label: 'Mobile App',
    category: 'client',
    defaultSize: { width: 170, height: 95 },
    defaultIcon: 'mobile',
    description: 'iOS / Android Native mobile application',
  },
  api_gateway: {
    type: 'api_gateway',
    defaultShape: 'gateway_ribbon',
    label: 'API Gateway',
    category: 'network',
    defaultSize: { width: 220, height: 84 },
    defaultIcon: 'api_gateway',
    description: 'Reverse proxy, routing, rate limiting, and auth entrypoint',
  },
  load_balancer: {
    type: 'load_balancer',
    defaultShape: 'rounded_card',
    label: 'Load Balancer',
    category: 'network',
    defaultSize: { width: 170, height: 76 },
    defaultIcon: 'load_balancer',
    description: 'L4/L7 Traffic distribution proxy',
  },
  service: {
    type: 'service',
    defaultShape: 'bento_card',
    label: 'Microservice',
    category: 'compute',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'service',
    description: 'Stateless backend business logic service',
  },
  worker: {
    type: 'worker',
    defaultShape: 'bento_card',
    label: 'Background Worker',
    category: 'compute',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'worker',
    description: 'Asynchronous job processor or consumer',
  },
  server: {
    type: 'server',
    defaultShape: 'bento_card',
    label: 'Server Host',
    category: 'compute',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'server',
    description: 'Dedicated server or virtual machine instance',
  },
  container: {
    type: 'container',
    defaultShape: 'bento_card',
    label: 'Container Pod',
    category: 'compute',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'container',
    description: 'Docker container or Kubernetes pod',
  },
  database: {
    type: 'database',
    defaultShape: 'data_cylinder',
    label: 'SQL Database',
    category: 'storage',
    defaultSize: { width: 168, height: 110 },
    defaultIcon: 'database',
    description: 'Relational or transactional SQL database',
  },
  postgresql: {
    type: 'postgresql',
    defaultShape: 'data_cylinder',
    label: 'PostgreSQL',
    category: 'storage',
    defaultSize: { width: 168, height: 110 },
    defaultIcon: 'postgresql',
    description: 'ACID transactional Postgres database',
  },
  cache: {
    type: 'cache',
    defaultShape: 'data_cylinder',
    label: 'In-Memory Cache',
    category: 'cache',
    defaultSize: { width: 168, height: 110 },
    defaultIcon: 'cache',
    description: 'Distributed memory caching tier',
  },
  redis: {
    type: 'redis',
    defaultShape: 'data_cylinder',
    label: 'Redis Cache',
    category: 'cache',
    defaultSize: { width: 168, height: 110 },
    defaultIcon: 'redis',
    description: 'In-memory Redis key-value cache and store',
  },
  queue: {
    type: 'queue',
    defaultShape: 'event_stream',
    label: 'Message Queue',
    category: 'messaging',
    defaultSize: { width: 220, height: 88 },
    defaultIcon: 'queue',
    description: 'FIFO message buffer or job queue',
  },
  kafka: {
    type: 'kafka',
    defaultShape: 'event_stream',
    label: 'Kafka Event Log',
    category: 'messaging',
    defaultSize: { width: 220, height: 88 },
    defaultIcon: 'kafka',
    description: 'Distributed partitioned commit log and event stream',
  },
  object_storage: {
    type: 'object_storage',
    defaultShape: 'bento_card',
    label: 'Object Storage',
    category: 'storage',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'object_storage',
    description: 'S3 / Blob storage for files and assets',
  },
  cdn: {
    type: 'cdn',
    defaultShape: 'bento_card',
    label: 'CDN Edge',
    category: 'network',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'cdn',
    description: 'Global content delivery network edge cache',
  },
  search: {
    type: 'search',
    defaultShape: 'data_cylinder',
    label: 'Search Engine',
    category: 'storage',
    defaultSize: { width: 168, height: 110 },
    defaultIcon: 'search',
    description: 'Elasticsearch / OpenSearch indexing cluster',
  },
  cloud: {
    type: 'cloud',
    defaultShape: 'cloud',
    label: 'Cloud VPC',
    category: 'network',
    defaultSize: { width: 180, height: 100 },
    defaultIcon: 'cloud',
    description: 'Public or private cloud boundary',
  },
  monitoring: {
    type: 'monitoring',
    defaultShape: 'rounded_card',
    label: 'Metrics & Logs',
    category: 'monitoring',
    defaultSize: { width: 170, height: 76 },
    defaultIcon: 'monitoring',
    description: 'Observability, tracing, and metric collection',
  },
  lock: {
    type: 'lock',
    defaultShape: 'rounded_card',
    label: 'Auth & Secrets',
    category: 'security',
    defaultSize: { width: 170, height: 76 },
    defaultIcon: 'lock',
    description: 'Authentication provider, vault, or HSM',
  },
  code: {
    type: 'code',
    defaultShape: 'serverless_function',
    label: 'Function / Script',
    category: 'compute',
    defaultSize: { width: 200, height: 92 },
    defaultIcon: 'code',
    description: 'Serverless function or cron execution',
  },
  custom: {
    type: 'custom',
    defaultShape: 'rounded_card',
    label: 'Custom Block',
    category: 'general',
    defaultSize: { width: 170, height: 80 },
    defaultIcon: 'service',
    description: 'User-defined custom architecture element',
  },
};

export function getNodeDefinition(type: NodeType): NodeDefinition {
  return nodeDefinitions[type] ?? nodeDefinitions['service'];
}
